### PR TITLE
check cloning element

### PR DESCRIPTION
**Pull request by Katochimoto**

### CODE REVIEW

**Comment by ebidel** [comment]
Before this PR can be merged, please sign the CLA. See the [CONTRIBUTING](http://polymer.github.io/CONTRIBUTORS.txt) guide.

**Comment by ebidel** [comment]
Thanks for signing the CLA!

**Comment by Katochimoto** [comment]
You are welcome! :)

**Comment by Katochimoto** [comment]
https://github.com/Polymer/CustomElements/blob/master/src/CustomElements.js#L34

https://github.com/Polymer/CustomElements/pull/118/files

Сhanges not found %) they really merged?

**Comment by sorvell** [comment]
Github seems to have gotten mixed up. We merged the custom event improvement but not the Mozilla fix. I'd rather not merge this right now since it addresses unreleased behavior. 

I'd prefer to file a bug on Mozilla's implementation.

**Comment by Katochimoto** [comment]
Yes, it would be better..
https://bugzilla.mozilla.org/show_bug.cgi?id=1050113

**Pull request merged**
