### PR TITLE
Wrap the document, and handle null

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by jakemac53** [comment]
@jmesserly I tested doing this as you suggested yesterday and it makes all the tests pass, ptal.

**Comment by jmesserly** [comment]
Ah, I was thinking to do it on the Dart side (web_components package). There we know platform.js is included and we have ShadowDOM. We don't make that assumption here.

Last I heard @sorvell is working on a JS fix. I offered to help but he seemed eager to do it :)

**Comment by sorvell** [comment]
lgtm. I was hoping to wrap (hah!) this into some other refactoring I want to do but it's going to take me a bit longer. This fix seems fine for now.

**Comment by jmesserly** [comment]
Do we have any concerns about x-tags or other users that consume CustomElements without ShadowDOM polyfill?

**Comment by jmesserly** [comment]
(Actually even SD polyfill doesn't put wrapIfNeeded on window. That must come from platform.JS)

**Comment by sorvell** [comment]
There's direct support in the CE polyfill for this (
https://github.com/Polymer/CustomElements/blob/master/src/Observer.js#L220
).

**Pull request merged**
