### PR TITLE
Make sure we follow the spec's native prototype resolution for IE10 proto-mixin

### PR DESCRIPTION
**Pull request by dfreedm**
Fixes #108

### CODE REVIEW

**Comment by arv** [comment]
Can you add a test too?

**Comment by dfreedm** [comment]
Rebase'd

**Comment by arv** [comment]
LGTM

**Comment by josh** [comment]
Thanks!

Already got it shipped.

**before**

screen shot 2014-05-19 at 1 38 08 pm

**after**

screen shot 2014-05-19 at 1 40 43 pm

**Comment by sjmiles** [comment]
Seems like you just allowed claiming an element extends `button` while not actually having `HTMLButtonElement` prototype on it's chain.

This is not acceptable in my opinion. If the spec allows this, then the spec is broken.

**Comment by josh** [comment]
> Seems like you just allowed claiming an element extends button while not actually having HTMLButtonElement prototype on it's chain.

We're extending the `<time>` tag. However, `HTMLTimeElement` isn't available in IE. Its still an unknown element so we just extend `HTMLElement`.

**Comment by sjmiles** [comment]
> We're extending the <time> tag. However, HTMLTimeElement isn't available

This is not a problem case, and is not relevant to any of these changes.

The only problem, is when you extend an element that DOES have a prototype, and then you do not include that prototype.

This will cause errors eventually, hiding it at CustomElement level is not doing anyone any favors.

**Pull request merged**
